### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by FlyGoat** [mycncart/mycncart#63]
1、安装界面的英文语言包没写完就不要有这个选项啊，安装的时候遇到满屏空白谁不是懵逼的。
2、你们在后台首页放个qq群我忍了，但麻烦不要安装好之后出现那么一坨测试数据，不能忍啊。

**Comment by mycncart** [comment]
感谢您的建议

**Comment by BlankRain** [comment]
哈哈哈…… 这个问题解决了么?

**Comment by k1988** [comment]
建议sql拆成两个，一个是结构一个是数据，安装时加个勾选项`是否使用测试数据`。
