### ISSUE TITLE
后台：报告-在线会员功能存在问题

### ISSUE THREAD

**Issue by cheasin** [mycncart/mycncart#82]
在网站后台的“报告”功能中，即使会员登录了，“在线会员”功能也不显示在线会员；另外，“检索会员”功能也不可使用。

**Comment by brunoxu** [comment]
![image](https://cloud.githubusercontent.com/assets/1411063/18544677/5d7ee2ca-7b68-11e6-9c8b-586096cc56b2.png)
请设置下这个项试试看有没有效果。

在系统设置的选项tab里面可以找到。

**Comment by brunoxu** [comment]
同样的问题还存在于后台首页控制面板和通知区域。

![image](https://cloud.githubusercontent.com/assets/1411063/18544769/c7d83734-7b68-11e6-8b13-7937a1db1c52.png)

![image](https://cloud.githubusercontent.com/assets/1411063/18544783/d349e50e-7b68-11e6-931f-d3a3763733d4.png)

**Comment by cheasin** [comment]
按照brunoxu提供的方法，可以显示了，需要在系统设置-选项中设置，系统默认的设置是关闭在线会员显示的，开启就可以了。

**Comment by mycncart** [comment]
Thank Bruno and Cheasin, will add it in tutorial.
